# Generated by Django 5.1.4 on 2025-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=100)),
                ('vibration', models.FloatField()),
                ('temperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('last_maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('up_time', models.IntegerField()),
                ('down_time', models.IntegerField()),
                ('factory_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_training_count', models.IntegerField(default=0)),
                ('last_trained_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=10)),
                ('factory_id', models.CharField(max_length=10)),
                ('factory_name', models.CharField(max_length=100)),
                ('machines', models.ManyToManyField(to='predictixApp.machine')),
            ],
        ),
    ]
