# Generated by Django 5.1.4 on 2025-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=100)),
                ('vibration', models.FloatField()),
                ('temperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('last_maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('up_time', models.IntegerField()),
                ('down_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mac',
        ),
    ]
