# Generated by Django 5.1.4 on 2025-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('machine', models.IntegerField()),
                ('machine_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('last_maintenance_days', models.IntegerField()),
                ('total_maintenance_cost', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('vibration', models.FloatField()),
                ('energy_consumption', models.FloatField()),
                ('noise_level', models.FloatField()),
                ('humidity', models.FloatField()),
                ('operating_hours', models.IntegerField()),
                ('fault', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Machine Histories',
            },
        ),
        migrations.RemoveField(
            model_name='factory',
            name='machines',
        ),
        migrations.DeleteModel(
            name='ModelTrainingMetadata',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
