# Generated by Django 5.1.4 on 2025-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0003_modeltrainingmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='factory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=10)),
                ('factory_id', models.CharField(max_length=10)),
                ('factory_name', models.CharField(max_length=100)),
                ('machines', models.ManyToManyField(to='predictixApp.machine')),
            ],
        ),
    ]
