# Generated by Django 5.1.4 on 2025-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('admin_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='factories',
            field=models.ManyToManyField(related_name='machines', to='predictixApp.factory'),
        ),
    ]
