# Generated by Django 5.1.4 on 2025-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0004_factory_machine_factories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.IntegerField(unique=True),
        ),
    ]
