# Generated by Django 5.1.5 on 2025-01-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0006_machine_prediction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_threshold', models.FloatField(default=100)),
                ('pressure_threshold', models.FloatField(default=100)),
                ('vibration_threshold', models.FloatField(default=100)),
                ('humidity_threshold', models.FloatField(default=100)),
                ('noise_level_threshold', models.FloatField(default=100)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='predictixApp.machine')),
            ],
        ),
    ]
