# Generated by Django 5.1.5 on 2025-01-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictixApp', '0007_machinethreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='predictixApp.factory')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_head', to='predictixApp.machine')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_source', to='predictixApp.machine')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_target', to='predictixApp.machine')),
            ],
        ),
    ]
